In [2]:
import numpy as np

In [3]:
#creat 1d array
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
ar=np.array((4,5,6,7,8,9))
ar

array([4, 5, 6, 7, 8, 9])

In [6]:
# 2d array
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
# access array element
ar[2]

6

In [9]:
arr2[1,2]

8