In [1]:
import numpy as np

In [2]:
#ones()=create nd array of all values 1
arr=np.ones(4)
arr

array([1., 1., 1., 1.])

In [6]:
arr1=np.ones((2,2))
arr1

array([[1., 1.],
       [1., 1.]])

In [7]:
# zeros()=create nd array of all values 0
arr2=np.zeros(2)
arr2

array([0., 0.])

In [8]:
#eye=create identiti matrix
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [12]:
#round=round up mdecimal numbers
arr3=np.array([1.34,4.8567])
np.round(arr3,1)

array([1.3, 4.9])

In [13]:
#linspace()=generates evenly spaced numbers over a specified interval by the first two arguments of the function and the third argument specify the number of samples to be granted


In [16]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])