In [3]:
import numpy as np

In [2]:
# mathematical operations
# 1 trignometric function
# 2 lograthmic function
# 3 inverse function
# 4 exponential function
# 5 statical function


In [4]:
arr=np.array([1,3,5,2,6])


In [5]:
#cosine value of each element
np.cos(arr)

array([ 0.54030231, -0.9899925 ,  0.28366219, -0.41614684,  0.96017029])

In [6]:
# log
np.log(arr)

array([0.        , 1.09861229, 1.60943791, 0.69314718, 1.79175947])

In [7]:
#mean
np.mean(arr)

3.4

In [8]:
#median
np.median(arr)

3.0

In [9]:
#standard deviation
np.std(arr)

1.8547236990991407

In [10]:
np.exp(arr)

array([  2.71828183,  20.08553692, 148.4131591 ,   7.3890561 ,
       403.42879349])

In [11]:
# arthematic operation

In [12]:
arr1=np.array([2,4,6,8,2])
arr2=np.array([3,6,1,5,2])

In [13]:
arr1+arr2

array([ 5, 10,  7, 13,  4])

In [14]:
arr1-arr2

array([-1, -2,  5,  3,  0])

In [15]:
arr1*arr2

array([ 6, 24,  6, 40,  4])